name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
          # Browse URL: https://github.com/coq-community/docker-coq/wiki#supported-tags
          # to get the list of supported (coq, ocaml) versions in coqorg/coq.
          coq_version:
            - '8.13'
            - 'dev'
          ocaml_version:
            - '4.07-flambda'
            - '4.11-flambda'
      max-parallel: 4
      # Don't cancel all in-progress jobs if one matrix job fails:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'cpdt.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          export: 'OPAMWITHTEST'
        env:
          OPAMWITHTEST: 'true'
